% -------------------------------------------------------------------
%  Generated by MATLAB on 3-Dec-2025 16:33:18
%  MATLAB version: 24.2.0.2923080 (R2024b) Update 6
% -------------------------------------------------------------------
                                                     

Sample_Time = 0.0001;

Sig = Simulink.Signal;
Sig.CoderInfo.StorageClass = 'Auto';
Sig.Description = '';
Sig.DataType = 'auto';
Sig.Min = [];
Sig.Max = [];
Sig.DocUnits = '';
Sig.Dimensions = -1;
Sig.DimensionsMode = 'auto';
Sig.Complexity = 'auto';
Sig.SampleTime = -1;
Sig.InitialValue = '';

Sig1 = Simulink.Signal;
Sig1.CoderInfo.StorageClass = 'Auto';
Sig1.Description = '';
Sig1.DataType = 'auto';
Sig1.Min = [];
Sig1.Max = [];
Sig1.DocUnits = '';
Sig1.Dimensions = -1;
Sig1.DimensionsMode = 'auto';
Sig1.Complexity = 'auto';
Sig1.SampleTime = -1;
Sig1.InitialValue = '';

